export const fakeVideos = [
  {
    thumbnailURL: "https://example.com/video1_thumbnail.jpg",
    videoURL: "https://www.youtube.com/channel/techtalks",
    videoTitle: "Steve Jobs - The Visionary Leader",
    videoViews: 126745,
    videoLikes: 9876,
    videoComments: 543,
    eventDate: "July 15, 2023",
    publishedDate: "July 20, 2023",
    channelThumbnailURL: "https://example.com/channel1_thumbnail.jpg",
    channelName: "Tech Talks",
    channelURL: "https://www.youtube.com/channel/techtalks",
    channelSubscribers: 256890,
  },
  {
    thumbnailURL: "https://example.com/video2_thumbnail.jpg",
    videoURL: "https://www.youtube.com/channel/techtalks",
    videoTitle: "The Untold Story of Steve Jobs",
    videoViews: 37651,
    videoLikes: 2457,
    videoComments: 99,
    eventDate: "August 5, 2023",
    publishedDate: "August 10, 2023",
    channelThumbnailURL: "https://example.com/channel1_thumbnail.jpg",
    channelName: "Tech Talks",
    channelURL: "https://www.youtube.com/channel/techtalks",
    channelSubscribers: 256890,
  },
  {
    thumbnailURL: "https://example.com/video3_thumbnail.jpg",
    videoURL: "https://www.youtube.com/channel/innovatenow",
    videoTitle: "Steve Jobs: Building a Legacy",
    videoViews: 98732,
    videoLikes: 6532,
    videoComments: 356,
    eventDate: "September 2, 2023",
    publishedDate: "September 7, 2023",
    channelThumbnailURL: "https://example.com/channel2_thumbnail.jpg",
    channelName: "Innovate Now",
    channelURL: "https://www.youtube.com/channel/innovatenow",
    channelSubscribers: 189754,
  },
  {
    thumbnailURL: "https://example.com/video4_thumbnail.jpg",
    videoURL: "https://www.youtube.com/channel/geekworld",
    videoTitle: "Steve Jobs: The Journey of a Tech Icon",
    videoViews: 156820,
    videoLikes: 9870,
    videoComments: 465,
    eventDate: "October 10, 2023",
    publishedDate: "October 15, 2023",
    channelThumbnailURL: "https://example.com/channel3_thumbnail.jpg",
    channelName: "Geek World",
    channelURL: "https://www.youtube.com/channel/geekworld",
    channelSubscribers: 307632,
  },
  {
    thumbnailURL: "https://example.com/video5_thumbnail.jpg",
    videoURL: "https://www.youtube.com/channel/techinnovators",
    videoTitle: "Steve Jobs: Inspiring the World",
    videoViews: 237850,
    videoLikes: 17654,
    videoComments: 998,
    eventDate: "November 20, 2023",
    publishedDate: "November 25, 2023",
    channelThumbnailURL: "https://example.com/channel4_thumbnail.jpg",
    channelName: "Tech Innovators",
    channelURL: "https://www.youtube.com/channel/techinnovators",
    channelSubscribers: 412567,
  },
  {
    thumbnailURL: "https://example.com/video6_thumbnail.jpg",
    videoURL: "https://www.youtube.com/channel/techtalks",
    videoTitle: "Steve Jobs: The Creative Genius",
    videoViews: 87452,
    videoLikes: 5301,
    videoComments: 201,
    eventDate: "December 5, 2023",
    publishedDate: "December 10, 2023",
    channelThumbnailURL: "https://example.com/channel1_thumbnail.jpg",
    channelName: "Tech Talks",
    channelURL: "https://www.youtube.com/channel/techtalks",
    channelSubscribers: 256890,
  },
  {
    thumbnailURL: "https://example.com/video7_thumbnail.jpg",
    videoURL: "https://www.youtube.com/channel/innovationhub",
    videoTitle: "Steve Jobs: Revolutionizing Technology",
    videoViews: 326900,
    videoLikes: 25438,
    videoComments: 1400,
    eventDate: "January 10, 2024",
    publishedDate: "January 15, 2024",
    channelThumbnailURL: "https://example.com/channel5_thumbnail.jpg",
    channelName: "Innovation Hub",
    channelURL: "https://www.youtube.com/channel/innovationhub",
    channelSubscribers: 548912,
  },
  {
    thumbnailURL: "https://example.com/video8_thumbnail.jpg",
    videoURL: "https://www.youtube.com/channel/geekworld",
    videoTitle: "Steve Jobs: The Legacy Continues",
    videoViews: 59031,
    videoLikes: 4673,
    videoComments: 267,
    eventDate: "February 20, 2024",
    publishedDate: "February 25, 2024",
    channelThumbnailURL: "https://example.com/channel3_thumbnail.jpg",
    channelName: "Geek World",
    channelURL: "https://www.youtube.com/channel/geekworld",
    channelSubscribers: 307632,
  },
  {
    thumbnailURL: "https://example.com/video9_thumbnail.jpg",
    videoURL: "https://www.youtube.com/channel/techinsights",
    videoTitle: "Steve Jobs: The Man Behind Apple",
    videoViews: 129870,
    videoLikes: 9285,
    videoComments: 501,
    eventDate: "March 5, 2024",
    publishedDate: "March 10, 2024",
    channelThumbnailURL: "https://example.com/channel6_thumbnail.jpg",
    channelName: "Tech Insights",
    channelURL: "https://www.youtube.com/channel/techinsights",
    channelSubscribers: 175943,
  },
];
